const projects = [
  {
    id: "1",
    clientId: "1",
    name: "Ecommerce Website",
    desc: "This is a ecommerce website for a local store",
    status: "In Progress",
  },
  {
    id: "2",
    clientId: "2",
    name: "Dating App",
    desc: "This is a dating app for a singles ready to mingle",
    status: "In Progress",
  },
  {
    id: "3",
    clientId: "3",
    name: "SEO Project",
    desc: "This is a SEO project guidline for setting up a website",
    status: "In Progress",
  },
  {
    id: "4",
    clientId: "4",
    name: "Design Prototype",
    desc: "This is a design prototype for a new product",
    status: "Done",
  },
  {
    id: "5",
    clientId: "5",
    name: "Auction Website",
    desc: "This is a auction website for a brand engaging in imports and exports",
    status: "In Progress",
  },
];

const clients = [
  {
    id: "1",
    name: "John Doe",
    email: "johndoe@gmail.com",
    phone: "232-456-7890",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zip: "10001",
    country: "USA",
    company: "ABC Company",
  },
  {
    id: "2",
    name: "Tony Stark",
    email: "ironman@gmail.com",
    phone: "132-456-9745",
    address: "45 Manhanttan St",
    city: "New York",
    state: "NY",
    zip: "53889",
    country: "USA",
    company: "Stark Industries",
  },
  {
    id: "3",
    name: "Bruce Wayne",
    email: "bruce@gmail.com",
    phone: "732-406-9742",
    address: "21 Gotham St",
    city: "Gotham",
    state: "NY",
    zip: "64209",
    country: "USA",
    company: "Wayne Enterprises",
  },
  {
    id: "4",
    name: "Clark Kent",
    email: "superman@gmail.com",
    phone: "432-656-5923",
    address: "94 Metropolis St",
    city: "Metropolis",
    state: "NY",
    zip: "74903",
    country: "USA",
    company: "Kent Company",
  },
  {
    id: "5",
    name: "Thor Odison",
    email: "thorthunder@gmail.com",
    phone: "032-401-7820",
    address: "29 Asgard St",
    city: "Asgard",
    state: "Asgard",
    zip: "028545",
    country: "Asgard",
    company: "Odinson Company",
  },
];

module.exports = { projects, clients };
